name: Arduino CLI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  compile-examples:
    name: Compile examples
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - sketch: examples/Basic
            fqbn: rp2040:rp2040:rpipico2
            additional_urls: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$PWD/bin" >> "$GITHUB_PATH"

      - name: Install Arduino cores
        run: |
          arduino-cli core update-index --additional-urls ${{ matrix.additional_urls }}
          arduino-cli core install rp2040:rp2040 --additional-urls ${{ matrix.additional_urls }}

      - name: Compile ${{ matrix.sketch }}
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} --library . ${{ matrix.sketch }}
